
#--------------------------------------------------#
# Generation of boolean models                     #
#--------------------------------------------------#

source_boolean_models_dir: "source_data/base_boolean_models_v1"
mutated_boolean_models_dir: "results/boolean_models/mutated_models_v1"
target_number_of_models: 2400