#--------------------------------------------------#
# Generation of boolean models                     #
#--------------------------------------------------#

source_boolean_models_dir: "source_data/base_boolean_models_v1"
base_pool_dir: "results/boolean_models/base_pool"
mutated_boolean_models_dir: "results/boolean_models/mutated"
target_number_of_models: 2400

MIN_DISTANCE: 0.15 # Min. distance threshold to the closest existing model
MAX_TESTED: 200000 # Quit after testing this number of mutations

MUTATION_P: [
    0.15,  #Switch nodes logic
    0.26,   #Replace logical operator
    0.228,  #Replace node inside logic
    0.25,   #Negate subexpression
    0.01,   #add_input_to_logic 
    0.002,    #Add node
    0.1,     #randomize_node_logic
    0.00    #randomize parameter
]
MAX_CREATED_NODES: 45 # Max number of new nodes in the mutated model. It prevents models from growing too much.
MIN_MUTATIONS: 10
MAX_MUTATIONS: 2000

#--------------------------------------------------#
# Sensitivity Analysis / Sampling                  #
#--------------------------------------------------#

sampling_dir: "results/sampling"
sampling_number_of_contexts: 2 #TODO: adjust
sampling_number_of_subjects: 2

# Remote execution settings (set use_remote to true to enable)
use_remote: false
remote_url: null  # e.g., "user@hpc-server.domain"
remote_results_path: null  # e.g., "/home/user/results"
remote_failed_path: null  # e.g., "/home/user/failed"
remote_temp_path: null  # e.g., "/home/user/temp"
max_jobs_stop: 480
max_jobs_resume: 210

#--------------------------------------------------#
# Filtering of models                              #
#--------------------------------------------------#
filtering_output_dir: "results/filtering"
mean_threshold: 0.0
abs_std_threshold: 30.0
norm_std_threshold: 0.2