
#--------------------------------------------------#
# Generation of boolean models                     #
#--------------------------------------------------#

source_dir: "source_data/base_boolean_models_v1"
