
configfile: "config/config.yaml"

# Boolean Model generation rules
# -----------------------------------------------------
include: "rules/boolean_models_mutations.smk"

# Sensitivity Analysis and model filtering rules
# -----------------------------------------------------
include: "rules/boolean_models_filtering.smk"