#--------------------------------------------------#
# Generation of boolean models                     #
#--------------------------------------------------#

base_pool_dir: "../../results/boolean_models/base_pool"
optimization_results_dir: "../../results/optimization"

#--------------------------------------------------#
# Remote execution                                 #
#--------------------------------------------------#
REMOTE_HPC_RESULTS_PATH: "masera/results_new_dir"
REMOTE_HPC_FAILED_PATH: "masera/failed_jobs"
HPC_TEMP_PATH: "masera/jobs"
HPC_LOGIN: "rsmeriglio@hpc-legionlogin.polito.it"
HPC_SCRIPT_NAME: "masera/run_job.sh"
POLLING_ATTEMPTS: 10
POLLING_INTERVAL_SECONDS: 60
