#--------------------------------------------------#
# Generation of boolean models                     #
#--------------------------------------------------#

source_boolean_models_dir: "../../data/reference_models"
base_pool_dir: "../../data/boolean_models/base_pool"
mutated_boolean_models_dir: "../../data/boolean_models/mutated"
target_number_of_models: 2115
NUM_GENERICS_BY_FAMILY: 12

MIN_DISTANCE: 0.15 # Min. distance threshold to the closest existing model
MAX_TESTED: 200000 # Quit after testing this number of mutations

MUTATION_P: [
    0.15,  #Switch nodes logic
    0.26,   #Replace logical operator
    0.228,  #Replace node inside logic
    0.25,   #Negate subexpression
    0.01,   #add_input_to_logic 
    0.002,    #Add node
    0.1,     #randomize_node_logic
    0.00    #randomize parameter
]
MAX_CREATED_NODES: 45 # Max number of new nodes in the mutated model. It prevents models from growing too much.
MIN_MUTATIONS: 10
MAX_MUTATIONS: 2000


#--------------------------------------------------#
# Sensitivity Analysis / Sampling                  #
#--------------------------------------------------#

sampling_dir: "../../results/sampling"
sampling_number_of_contexts: 215
sampling_number_of_subjects: 2115

# Remote execution settings (set use_remote to true to enable)
use_remote: false
remote_user: "rsmeriglio"  # e.g., "user"
remote_host: "hpc-legionlogin.polito.it"  # e.g., "hpc-server.domain"
remote_url: "rsmeriglio@hpc-legionlogin.polito.it"  # e.g., "user@hpc-server.domain"
remote_results_path:  "/home/rsmeriglio/masera/results_new_dir"  # e.g., "/home/user/results"
remote_failed_path: "/home/rsmeriglio/masera/failed_jobs"  # e.g., "/home/user/failed"
remote_temp_path: "/home/rsmeriglio/masera/jobs"  # e.g., "/home/user/temp"
hpc_script_name: "masera/run_job.sh"
max_jobs_stop: 480
max_jobs_resume: 210

#--------------------------------------------------#
# Filtering of models                              #
#--------------------------------------------------#
filtering_output_dir: "../../results/filtering" # Store there filtering related
filtered_output_dir: "../../data/boolean_models/filtered" # Store the final, filtered dataset and a manifest file
mean_threshold: 0.0
abs_std_threshold: 10 #30.0
norm_std_threshold: 0.05 #0.2


#--------------------------------------------------#
# Static distance measures                         #
#--------------------------------------------------#
static_distance_dir: "../../results/static_distances"
STATIC_DISTANCE_NUM_PROCESSES: 32
STATIC_DISTANCE_MAX_GRAPHS: -1 # -1 to use all graphs
STATIC_DISTANCE_USE_GLOBAL: 0
STATIC_DISTANCE_MEASURES: 
    - "DeltaCon"
    - "IpsenMikhailov"
    - "QuantumJSD"


#--------------------------------------------------#
# Data extraction                                  #
#--------------------------------------------------#
extraction_grid_size: 2000
extraction_max_concurrent: 90
extraction_save_time: 60
extraction_max_retries: 1
extraction_stale_minutes: 1500
extraction_results_dir: "../../data/multiscale_simulations"
extraction_init_pos_json: "../../data/multiscale_simulations/initial_positions.json"
extraction_times_dir: "../../data/multiscale_simulations/times"

# Extra HPC settings
extraction_remote_base: "/home/rsmeriglio/masera/meta_model_rick" # Base directory on the HPC
extraction_remote_results: "/home/rsmeriglio/masera/meta_model_rick/results" # Directory on the HPC where to store results
extraction_remote_script: "/home/rsmeriglio/masera/meta_model_rick/run_job.sh"