configfile: "config/config.yaml"

# Default rule - defines final outputs
#rule all:
#    input:
#        static_distances = "results/boolean_models/static_distance",
#        filtering = config["filtering_output_dir"]

# Boolean Model generation rules
# -----------------------------------------------------
#include: "rules/boolean_models_mutations.smk"



rule test_hpc_jobs:
    output:
        OUTPUT_DIR = directory("temp")
    params:
        POLLING_ATTEMPTS = config["POLLING_ATTEMPTS"],
        POLLING_INTERVAL_SECONDS = config["POLLING_INTERVAL_SECONDS"],
        BOOLEAN_MODEL_POOL = config["base_pool_dir"],
        REMOTE_HPC_RESULTS_PATH = config["REMOTE_HPC_RESULTS_PATH"],
        REMOTE_HPC_FAILED_PATH = config["REMOTE_HPC_FAILED_PATH"],
        HPC_TEMP_PATH = config["HPC_TEMP_PATH"],
        HPC_LOGIN = config["HPC_LOGIN"],
        HPC_SCRIPT_NAME = config["HPC_SCRIPT_NAME"]

    shell:
        """
        python workflow/scripts/test_hpc_jobs.py \
            --output-dir {output.OUTPUT_DIR} \
            --polling-attempts {params.POLLING_ATTEMPTS} \
            --polling-interval-seconds {params.POLLING_INTERVAL_SECONDS} \
            --remote-hpc-results-path {params.REMOTE_HPC_RESULTS_PATH} \
            --remote-hpc-failed-path {params.REMOTE_HPC_FAILED_PATH} \
            --hpc-temp-path {params.HPC_TEMP_PATH} \
            --hpc-login {params.HPC_LOGIN} \
            --hpc-script-name {params.HPC_SCRIPT_NAME} \
            --boolean-model-pool {params.BOOLEAN_MODEL_POOL}
        """

rule run_optimization:
    output:
        OUTPUT_DIR = directory(config["optimization_results_dir"]+ "/DE_budget{budget}_realfitness{real_fitness}__{family}_{model}")
    params:
        POLLING_ATTEMPTS = config["POLLING_ATTEMPTS"],
        POLLING_INTERVAL_SECONDS = config["POLLING_INTERVAL_SECONDS"],
        BOOLEAN_MODEL_POOL = config["base_pool_dir"],
        REMOTE_HPC_RESULTS_PATH = config["REMOTE_HPC_RESULTS_PATH"],
        REMOTE_HPC_FAILED_PATH = config["REMOTE_HPC_FAILED_PATH"],
        HPC_TEMP_PATH = config["HPC_TEMP_PATH"],
        HPC_LOGIN = config["HPC_LOGIN"],
        HPC_SCRIPT_NAME = config["HPC_SCRIPT_NAME"]

    shell:
        """
        python workflow/scripts/optimizer.py \
            --output-dir {output.OUTPUT_DIR} \
            --temp-output-dir . \
            --polling-attempts {params.POLLING_ATTEMPTS} \
            --polling-interval-seconds {params.POLLING_INTERVAL_SECONDS} \
            --remote-hpc-results-path {params.REMOTE_HPC_RESULTS_PATH} \
            --remote-hpc-failed-path {params.REMOTE_HPC_FAILED_PATH} \
            --hpc-temp-path {params.HPC_TEMP_PATH} \
            --hpc-login {params.HPC_LOGIN} \
            --hpc-script-name {params.HPC_SCRIPT_NAME} \
            --optimization-budget {wildcards.budget} \
            --real-fitness-estimation-budget {wildcards.real_fitness} \
            --model-family {wildcards.family} \
            --model-name {wildcards.model} \
            --boolean-model-pool {params.BOOLEAN_MODEL_POOL}
        """