configfile: "config/config.yaml"

# Default rule - defines final outputs
rule all:
    input:
        filtering = config["filtering_output_dir"],
        static_distances = config["static_distance_dir"],
        extraction = config["extraction_results_dir"] + "/multiscale_simulations_manifest.json"



# Boolean Model generation rules
# -----------------------------------------------------
include: "rules/boolean_models_mutations.smk"



# Sensitivity Analysis and model filtering rules
# -----------------------------------------------------
include: "rules/boolean_models_filtering.smk"

# Data Extraction 
# -----------------------------------------------------
include: "rules/data_extraction.smk"

# Individual Simulations Run
# -----------------------------------------------------
include: "rules/run_simulations.smk"